// app/light-saber/LightSaber.vue
<script setup lang="ts">
import * as THREE from 'three';
import { onMounted } from 'vue';
import { degToRad } from '~/app/triggonometry/deg-rad.utils';

const props = defineProps<{
  alpha: number;
  beta: number;
  gamma: number;
}>();
const container = ref<HTMLDivElement | null>(null);

onMounted(() => {
  const width = 300;
  const height = 300;
  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(75, width / height, 0.1, 1000);
  const axesHelper = new THREE.AxesHelper(5);
  scene.add(axesHelper);

  const renderer = new THREE.WebGLRenderer();
  renderer.setSize(300, 300);
  container.value?.appendChild(renderer.domElement);

  const geometry = new THREE.BoxGeometry(3, 1, 5);
  const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
  const cube = new THREE.Mesh(geometry, material);
  scene.add(cube);

  camera.position.z = 5;

  function animate() {
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
    cube.rotation.x = degToRad(props.beta);
    cube.rotation.y = degToRad(props.gamma);
    cube.rotation.z = degToRad(props.alpha);
  }
  animate();
});
</script>

<template>
  <p>Alpha: {{ props.alpha }}</p>
  <p>Beta: {{ props.beta }}</p>
  <p>Gamma: {{ props.gamma }}</p>
  <div ref="container" />
</template>

// src/components/LightSaber.svelte
<script lang="ts">
    import * as THREE from 'three';
    import {onMount} from "svelte";
    import {degToRad} from "../utils/deg-rad.utils";

    export let alpha, beta, gamma;

    let el;

    onMount(() => {
        const width = 300;
        const height = 300;
        const scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera( 75, width / height, 0.1, 1000 );

        const renderer = new THREE.WebGLRenderer();
        renderer.setSize( 300, 300 );
        el.appendChild( renderer.domElement );

        const geometry = new THREE.BoxGeometry( 1, 5, 1 );
        const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
        const cube = new THREE.Mesh( geometry, material );
        scene.add( cube );

        camera.position.z = 5;

        function animate() {
            requestAnimationFrame( animate );
            renderer.render( scene, camera );
            cube.rotation.x = degToRad(gamma);
            cube.rotation.y = degToRad(beta);
            cube.rotation.z = degToRad(alpha);
        }
        animate();
    })
</script>

<div bind:this={el}></div>
